#!/bin/bash

echo "=========================================="
echo "SPOTICS OAUTH FIX VERIFICATION"
echo "=========================================="
echo ""

echo "STEP 1: Set up environment variables in Railway"
echo "-------------------------------------------"
echo "1. Go to https://railway.app"
echo "2. Select your Spotics project"
echo "3. Click 'Variables' tab"
echo "4. Add these variables:"
echo ""
echo "   SPOTIFY_CLIENT_ID=<your_client_id>"
echo "   SPOTIFY_CLIENT_SECRET=<your_client_secret>"
echo "   SPOTIFY_REDIRECT_URI=https://spotics.insights.autos/api/auth/callback"
echo "   DATABASE_URL=<your_neon_connection_string>"
echo "   JWT_SECRET=$(openssl rand -base64 32)"
echo "   SESSION_COOKIE_NAME=spotics_session"
echo "   COOKIE_SECRET=$(openssl rand -base64 32)"
echo "   NODE_ENV=production"
echo "   CLIENT_URL=https://spotics.insights.autos"
echo "   APP_URL=https://spotics.insights.autos"
echo "   API_URL=https://spotics.insights.autos/api/v1"
echo ""
echo "5. Click 'Save' for each variable"
echo "6. Railway will auto-redeploy"
echo ""

echo "STEP 2: Configure Spotify Dashboard"
echo "-------------------------------------------"
echo "1. Go to https://developer.spotify.com/dashboard"
echo "2. Select your app"
echo "3. Click 'Settings'"
echo "4. Under 'Redirect URIs', add:"
echo "   https://spotics.insights.autos/api/auth/callback"
echo "5. Save changes"
echo ""

echo "STEP 3: Wait for Railway redeployment"
echo "-------------------------------------------"
echo "Wait 1-2 minutes for Railway to redeploy"
echo "You can check logs in Railway dashboard"
echo ""

echo "STEP 4: Test the OAuth flow"
echo "-------------------------------------------"
echo "Run these commands to verify:"
echo ""
echo "# Test OAuth endpoint (should return 302)"
echo "curl -I https://spotics.insights.autos/api/auth/login"
echo ""
echo "# Test callback endpoint (should return 400 for invalid state)"
echo "curl -I https://spotics.insights.autos/api/auth/callback?code=test&state=test"
echo ""
echo "# Visit the site"
echo "https://spotics.insights.autos"
echo ""
echo "Click 'Continue with Spotify' - should redirect to Spotify OAuth"
echo ""

echo "=========================================="
echo "IF STILL GETTING 'INVALID_CLIENT' ERROR:"
echo "=========================================="
echo ""
echo "This means SPOTIFY_CLIENT_SECRET is missing or incorrect."
echo ""
echo "Check Railway logs for:"
echo "  - Missing env vars error"
echo "  - Spotify auth errors"
echo ""
echo "Verify in Railway dashboard that:"
echo "  - All 11 variables are set"
echo "  - SPOTIFY_CLIENT_ID matches your Spotify app"
echo "  - SPOTIFY_CLIENT_SECRET matches your Spotify app"
echo "  - No typos in variable names"
echo ""
