build:
  env:
    - DATABASE_URL
    - SPOTIFY_CLIENT_ID
    - SPOTIFY_CLIENT_SECRET
    - SPOTIFY_REDIRECT_URI
    - JWT_SECRET
    - SESSION_COOKIE_NAME
    - COOKIE_SECRET
    - NODE_ENV
run:
  autoDeploy: true
  command: npm run build && npm start
